import Head from "next/head";
import { GetServerSideProps } from "next";
import { api } from "@/lib/axios";
import { ProductTypes } from "@/@types/product";
import Header from "@/components/Header";

interface DashboardProps {
  products: ProductTypes[];
}

export default function Dashboard({ products }: DashboardProps) {
  return (
    <>
      <Head>
        <title>Stock Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <section>
          <h1 className="text-2xl font-medium border-b-2 border-t-2 border-gray-300 py-4 mb-4">
            Lista de produtos
          </h1>

          <aside>
            <div className="grid mb-4 grid-cols-4">
              <strong>ID</strong>
              <strong>Nome</strong>
              <strong>Quantidade</strong>
              <strong>Preço</strong>
            </div>

            {products.map((product) => {
              return (
                <div key={product.id} className="grid grid-cols-4">
                  <strong>{product.id}</strong>
                  <strong>{product.name}</strong>
                  <strong>{product.amount}</strong>
                  <strong>{product.price}</strong>
                </div>
              );
            })}
          </aside>
        </section>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { "@stockManager:token": token } = ctx.req.cookies;

  try {
    const response = await api.get("/product/", {
      headers: {
        Authorization: `Token ${token}`,
      },
    });
    return {
      props: {
        products: response.data,
      },
    };
  } catch (error) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
};
